### ISSUE TITLE
Adapt for https://github.com/CentOS/centos-bootc/pull/259

### ISSUE THREAD

**Issue by cgwalters** [containers/podman-desktop-extension-bootc#129]
### Bug description

Let's start using the label here https://github.com/CentOS/centos-bootc/pull/259

### Operating system

any

### Version

next (development version)

**Comment by deboer-tim** [comment]
PR #130 up to add support for the new label, it's minor and we planned to release today anyway so this will be out soon.

I did not remove support for the old label since it will take some time for the new one to be prevalent; leaving this issue open as a reminder to do a second PR and remove it later.
