### ISSUE TITLE
drop 10 mins timeout when creating a disk image

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop-extension-bootc#315]
### Bug description

Can we drop the 10 mins timeout when creating a disk image?  I ran into it a number of times and expect more users to hit it.

### Operating system

macOS 14.4.1

### Version

next (development version)

**Comment by benoitf** [comment]
adding some pointers

https://github.com/containers/podman-desktop-extension-bootc/blob/6c0e75c2395416a1fb5d4542e6527d46b7959175/packages/backend/src/container-utils.ts#L136

https://github.com/containers/podman-desktop-extension-bootc/blob/6c0e75c2395416a1fb5d4542e6527d46b7959175/packages/backend/src/build-disk-image.ts#L196

**Comment by vrothberg** [comment]
All good alternatives to me.  I wouldn't know how it would turn into an infinite loop, so no timeout may be safe as well.

**Comment by deboer-tim** [comment]
PR up to increase to 20min. Hopefully that is enough, and I don't want to make it infinite as then you'd have a task in the task manager that you can never clear.

**Comment by cdrage** [comment]
@deboer-tim right now with bootc-image-builder their tests on M1 machines are finishing at 8 minutes. With other machines on Windows / Linux with less than optimal processors, I think IMHO we should do it for an hour.

Come to think of it, maybe we should actually add a "build time" column to the dashboard too?

**Comment by deboer-tim** [comment]
M1 Macs are 3 years old, and although they're fast they're not multiples of other machines. So 60min is a _lot_ of CPU time, but I've bumped the PR up to that.

**Comment by benoitf** [comment]
I think the best way would be to pickup a value and have a configuration property of the extension 

In case of timeout, say that if the issue happen , user can adjust the timeout to a different value

Because you'll always have someone reaching the timeout and from user POV it's frustrating if he can't adjust it

**Comment by deboer-tim** [comment]
You are right. I was hesitant to start adding configuration properties, but this is a good case where one is better. PR updated.

**Comment by vrothberg** [comment]
I am onboard with making it configurable but wonder why.  Does PD set timeouts for container builds?  Podman does not but maybe there's a history of BIB running into deadlocks?

**Comment by benoitf** [comment]
I did not introduce the timeout but I can comment on a general pattern
Usually on UI side you expect to know when it'll end and it should be in a 'reasonable amount of time'

and you want to be notified if for some reason it never finished in the 'expected timeframe'

**Comment by deboer-tim** [comment]
The length of container builds varies widely, but it tends to be short enough that users watches and knows when is 'too long' and will cancel it. For disk image builds we found it's a couple min for small builds, 5-10 for bigger builds, and beyond that it's probably something wrong... but since the user isn't going to wait around staring at it we wanted to have some way of eventually ending the task and notifying them.
Hopefully with the new default of 30min the user never even knows it's there, but since it is configurable they can always change it if they do expect longer builds.
