### ISSUE TITLE
checkbox UI

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop-extension-bootc#317]
### Is your enhancement related to a problem? Please describe

In Podman Desktop checkboxes have a dark mark inside the checkbox

![image](https://github.com/containers/podman-desktop-extension-bootc/assets/436777/bc6f47b6-3ea8-45c4-9d86-c33fd6f5b192)

but in bootc it's all purple
![image](https://github.com/containers/podman-desktop-extension-bootc/assets/436777/5c526652-1133-4c60-b472-721f71a5feb5)

### Describe the solution you'd like

have the same rendering than in Podman Desktop

**Comment by deboer-tim** [comment]
Forgot to document it here before: the Build page is not actually using the Checkbox component today. We could switch and it would fix the UI problem, but I was hesitant because the checkbox copied from Podman Desktop does not work well with Playwright (see https://github.com/containers/podman-desktop/pull/6023, where switching to it breaks E2E tests due to not working well with aria roles). E2E tests need to be able to pick image type and I didn't want to block this.

Initial I was thinking we should wait for fixed Checkbox in PD and use that, but maybe there's a short-term option like some minimal checkbox styling.

**Comment by benoitf** [comment]
ah ok I thought it was not rendering as expected due to some issues but if it's not using the component 🤣
